apiVersion: v1
kind: List
items:
  - kind: DeploymentConfig
    apiVersion: apps.openshift.io/v1
    metadata:
      name: fraud-app
      labels:
        svc: fraud-app
        app.openshift.io/runtime: python
    spec:
      replicas: 1
      template:
        metadata:
          labels:
            app: fraud-app
        spec:
          containers:
            - name: fraud-app
              image: >-
                image-registry.openshift-image-registry.svc:5000/fsi-fraud-detection-xops/fraud-app:latest
              #env:

              #resources:
              #  limits:
              #    cpu: "2"
              #    memory: 8Gi
              #  requests:
              #    cpu: "1"
              #    memory: 4Gi
              #envFrom:
              #  - configMapRef:
              #      name: fsi-fraud-detection-config

  - kind: Service
    apiVersion: v1
    metadata:
      name: fraud-app-svc
    spec:
      ports:
        - protocol: TCP
          port: 8080
          targetPort: 8080
      selector:
        app: fraud-app

  - kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      name: predict
    spec:
      to:
        kind: Service
        name: fraud-app-svc
        weight: 100
      port:
        targetPort: 8080
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Redirect
      wildcardPolicy: None
