kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: models
  labels:
    app: fsi-fraud-detection
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: gp2
  volumeMode: Filesystem
