kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: datalake
  labels:
    app: fsi-fraud-detection
    app-owner: fsi-fraud-detection
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp2
  volumeMode: Filesystem
