apiVersion: v1
kind: List
items:
  - kind: DeploymentConfig
    apiVersion: apps.openshift.io/v1
    metadata:
      name: simulator-notebook
      labels:
        svc: simulator-notebook
        app.openshift.io/runtime: python
    spec:
      replicas: 1
      template:
        metadata:
          labels:
            app: simulator-notebook
        spec:
          volumes:
            - name: datalake-archive
              persistentVolumeClaim:
                claimName: datalake
            - name: ml-models
              persistentVolumeClaim:
                claimName: models
          containers:
            - name: simulator-notebook
              image: >-
                image-registry.openshift-image-registry.svc:5000/fsi-fraud-detection-xops/simulator-notebook:latest
          
              resources:
                limits:
                  cpu: '2'
                  memory: 8Gi
                requests:
                  cpu: '1'
                  memory: 4Gi
              
              volumeMounts:
                - name: datalake-archive
                  mountPath: '/opt/app-root/data/archive'
                - name: ml-models
                  mountPath: '/opt/app-root/data/models'

              env:
                - name: JUPYTER_PORT
                  value: "8080"
                - name: JUPYTER_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: jupyter_password
                      name: simulator-notebook-secrets
              #envFrom:
              #  - configMapRef:
              #      name: fsi-fraud-detection-config

  - kind: Service
    apiVersion: v1
    metadata:
      name: simulator-notebook-svc
    spec:
      ports:
        - protocol: TCP
          port: 8080
          targetPort: 8080
      selector:
        app: simulator-notebook

  - kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      name: sim
    spec:
      to:
        kind: Service
        name: simulator-notebook-svc
        weight: 100
      port:
        targetPort: 8080
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Redirect
      wildcardPolicy: None