apiVersion: v1
kind: List
items:  
  - kind: ClusterTask
    apiVersion: tekton.dev/v1beta1
    metadata:
      name: run-notebook
    spec:
      params:
        - name: NOTEBOOKS
          type: string
          description: A list of Jupyter Notebooks to run.
        - name: PATH_CONTEXT
          description: The location of the path to run s2i from.
          default: .
          type: string
        - name: PAPERMILL_VERSION
          description: The version of Papermill to install.
          default: 2.3.4
      steps:
        - script: >
            #!/usr/bin/env sh

            set -eu

            cd $(params.PATH_CONTEXT)

            pip install -r requirements.txt

            pip install papermill==$(params.PAPERMILL_VERSION)

            papermill --log-output ${PARAM_NOTEBOOKS} output.ipynb
          env:
          - name: PARAM_PATH_CONTEXT
            value: $(params.PATH_CONTEXT)
          - name: PARAM_NOTEBOOKS
            value: $(params.NOTEBOOKS)
          #- name: PARAM_PAPERMILL_VERSION
          #  value: $(params.PAPERMILL_VERSION)
          image: ubi8/python-39
          name: 'run-notebooks'
          resources:
            requests:
              memory: 2Gi
              cpu: 1
            limits:
              memory: 8Gi
              cpu: 2
          volumeMounts:
            - mountPath: /gen-source
              name: gen-source
          workingDir: $(workspaces.source.path)
      volumes:
        - emptyDir: {}
          name: gen-source
      workspaces:
        - mountPath: /workspace/source
          name: source

  - kind: ClusterTask
    apiVersion: tekton.dev/v1beta1
    metadata:
      name: inspect
    spec:
      steps:
        - script: >
            #!/usr/bin/env sh

            set -eu

            ls -la /workspace/source
          image: ubi8/ubi-minimal
          name: ''
          resources: {}
          volumeMounts:
            - mountPath: /gen-source
              name: gen-source
          workingDir: $(workspaces.source.path)
      volumes:
        - emptyDir: {}
          name: gen-source
      workspaces:
        - mountPath: /workspace/source
          name: source