apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaBridge
metadata:
  name: transaction-bridge
  labels:
    app-owner: fsi-fraud-detection-kafka
  #namespace: fsi-fraud-detection
spec:
  http:
    port: 8080
  replicas: 1
  bootstrapServers: "transactions-kafka-bootstrap:9092"
