apiVersion: v1
kind: List
items:
  - kind: BuildConfig
    apiVersion: build.openshift.io/v1
    metadata:
      name: archive-svc
      labels:
        app: fsi-fraud-detection
        app.openshift.io/runtime: golang
    spec:
      runPolicy: Serial
      source:
        git:
          ref: develop
          uri: "https://github.com/redhat-capgemini-exchange/fsi-fraud-detection"
        type: Git
      strategy:
        type: Source
        sourceStrategy:
          from:
            kind: ImageStreamTag
            name: "golang-custom:1.16.12"
            #namespace: openshift
          env:
            - name: BUILD_DIR
              value: services/archive_svc
      output:
        to:
          kind: ImageStreamTag
          name: archive-svc:latest
      triggers:
        - type: GitHub
          github:
            secretReference:
              name: fsi-fraud-detection-xops-secrets
        - type: ImageChange
          imageChange: {}
        - type: ConfigChange
