apiVersion: v1
kind: List
items:
  - kind: DeploymentConfig
    apiVersion: apps.openshift.io/v1
    metadata:
      name: fraud-app
      labels:
        app: fraud-app
        app.openshift.io/runtime: python
        group: backend-apps
    spec:
      replicas: 1
      template:
        metadata:
          labels:
            app: fraud-app
            group: backend-apps
        spec:
          volumes:
            - name: fraud-model
              persistentVolumeClaim:
                claimName: models
          containers:
            - name: fraud-app
              image: >-
                image-registry.openshift-image-registry.svc:5000/fsi-fraud-detection-xops/fraud-app:latest
              env:
                - name: model_location
                  value: "/opt/app-root/data/models/model_latest.pkl"
                - name: tx_fraud_threshold
                  value: "0.8"
                - name: tx_fraud_scenario
                  value: "2"
                
              volumeMounts:
                - name: fraud-model
                  readOnly: true
                  mountPath: '/opt/app-root/data/models'

              #resources:
              #  limits:
              #    cpu: "2"
              #    memory: 8Gi
              #  requests:
              #    cpu: "1"
              #    memory: 4Gi
              #envFrom:
              #  - configMapRef:
              #      name: fsi-fraud-detection-config

  - kind: Service
    apiVersion: v1
    metadata:
      name: fraud-app-svc
    spec:
      ports:
        - protocol: TCP
          port: 8080
          targetPort: 8080
          name: api
      selector:
        app: fraud-app

  - kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      name: predict
    spec:
      to:
        kind: Service
        name: fraud-app-svc
        weight: 100
      port:
        targetPort: 8080
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Redirect
      wildcardPolicy: None
