apiVersion: v1
kind: List
items:
  - kind: DeploymentConfig
    apiVersion: apps.openshift.io/v1
    metadata:
      name: rules-app
      labels:
        app: rules-app
        app-owner: fsi-fraud-detection
        app.openshift.io/runtime: python
        group: backend-apps
    spec:
      replicas: 1
      template:
        metadata:
          labels:
            app: rules-app
            app-owner: fsi-fraud-detection
            group: backend-apps
        spec:
          containers:
            - name: rules-app
              image: >-
                image-registry.openshift-image-registry.svc:5000/fsi-fraud-detection-xops/rules-app:latest
              env:
                - name: tx_fraud_threshold
                  value: "220.0"
                - name: tx_fraud_scenario
                  value: "1"

              #resources:
              #  limits:
              #    cpu: "2"
              #    memory: 8Gi
              #  requests:
              #    cpu: "1"
              #    memory: 4Gi
              #envFrom:
              #  - configMapRef:
              #      name: fsi-fraud-detection-config

  - kind: Service
    apiVersion: v1
    metadata:
      name: rules-app-svc
      labels:
        app-owner: fsi-fraud-detection
    spec:
      ports:
        - protocol: TCP
          port: 8080
          targetPort: 8080
          name: api
      selector:
        app: rules-app

  - kind: Route
    apiVersion: route.openshift.io/v1
    metadata:
      name: validate
      labels:
        app-owner: fsi-fraud-detection
    spec:
      to:
        kind: Service
        name: rules-app-svc
        weight: 100
      port:
        targetPort: 8080
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Redirect
      wildcardPolicy: None
