apiVersion: v1
kind: List
items:
  - kind: DeploymentConfig
    apiVersion: apps.openshift.io/v1
    metadata:
      name: case-svc
      labels:
        svc: case-svc
        app-owner: fsi-fraud-detection
        app.openshift.io/runtime: golang
        group: integration-svc
        collect_metrics: "true"
    spec:
      selector:
        svc: case-svc
      replicas: 1
      template:
        metadata:
          labels:
            svc: case-svc
            app-owner: fsi-fraud-detection
            group: integration-svc
            collect_metrics: "true"
        spec:
          containers:
            - name: case-svc
              image: >-
                image-registry.openshift-image-registry.svc:5000/fsi-fraud-detection-xops/case-svc:latest
              imagePullPolicy: Always
              envFrom:
                - configMapRef:
                    name: fsi-fraud-detection-config
              env:
                - name: source_topic
                  value: "tx-fraud"
                - name: target_topic
                  value: "tx-archive"

                - name: client_id
                  value: "case_svc"
                - name: group_id
                  value: "case_svc"

  - kind: Service
    apiVersion: v1
    metadata:
      name: metrics-case-svc
      labels:
        app-owner: fsi-fraud-detection
    spec:
      ports:
        - protocol: TCP
          port: 2112
          targetPort: 2112
          name: metrics
      selector:
        svc: case-svc
      type: ClusterIP
