apiVersion: v1
kind: List
items:
  - kind: DeploymentConfig
    apiVersion: apps.openshift.io/v1
    metadata:
      name: router-svc
      labels:
        svc: router-svc
        app-owner: fsi-fraud-detection
        app.openshift.io/runtime: golang
        group: integration-svc
        collect_metrics: "true"
    spec:
      selector:
        svc: router-svc
      replicas: 1
      template:
        metadata:
          labels:
            svc: router-svc
            app-owner: fsi-fraud-detection
            group: integration-svc
            collect_metrics: "true"
        spec:
          containers:
            - name: router-svc
              image: >-
                image-registry.openshift-image-registry.svc:5000/fsi-fraud-detection-xops/router-svc:latest
              imagePullPolicy: Always
              envFrom:
                - configMapRef:
                    name: fsi-fraud-detection-config
              env:
                - name: source_topic
                  value: 'tx'
                  
                - name: archive_topic
                  value: 'tx-archive'
                - name: fraud_topic
                  value: 'tx-fraud'

                - name: rules_app_svc
                  value: "http://rules-app-svc.fsi-fraud-detection.svc.cluster.local:8080/validate"
                - name: fraud_app_svc
                  value: "http://fraud-app-svc.fsi-fraud-detection.svc.cluster.local:8080/predict"

                - name: client_id
                  value: 'router_svc'
                - name: group_id
                  value: 'router_svc'

  - kind: Service
    apiVersion: v1
    metadata:
      name: metrics-router-svc
      labels:
        app-owner: fsi-fraud-detection
    spec:
      ports:
        - protocol: TCP
          port: 2112
          targetPort: 2112
          name: metrics
      selector:
        svc: router-svc
      type: ClusterIP
